export const SET_INGREDIENTS='SET_INGREDIENTS';
export const ADD_INGREDIENT_AMOUNT='ADD_INGREDIENT_AMOUNT';
export const SUB_INGREDIENT_AMOUNT='SUB_INGREDEINT_AMOUNT';
export const FETCH_INGREDIENTS_FAILED = "FETCH_INGREDIENTS_FAILED";